name: Run Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive # fetches all submodules recursively

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set script permissions
      run: |
        chmod +x ./tsrc-dev
        chmod +x ./tsrc-dev.py

    - name: Create turbosrc.config from secret
      run: echo "${{ secrets.TURBOSRC_CONFIG }}" > ./turbosrc.config
      run: cat turbosrc.config

    - name: Run turbosrc init
      run: ./tsrc-dev init

    - name: Restart and test tsrc-dev
      run: |
        ./tsrc-dev restart
        sleep 10
        ./tsrc-dev test 7db9a demo execute_all
